/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserSignupRouteImport } from './routes/user/signup'
import { Route as UserLoginRouteImport } from './routes/user/login'
import { Route as UserGuestRouteImport } from './routes/user/guest'
import { Route as DashboardsUnemployedRouteImport } from './routes/dashboards/unemployed'
import { Route as DashboardsStudentRouteImport } from './routes/dashboards/student'
import { Route as DashboardsRetiredRouteImport } from './routes/dashboards/retired'
import { Route as DashboardsGuestRouteImport } from './routes/dashboards/guest'
import { Route as DashboardsEmployedRouteImport } from './routes/dashboards/employed'
import { Route as DashboardsLayoutRouteImport } from './routes/dashboards/_layout'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserSignupRoute = UserSignupRouteImport.update({
  id: '/user/signup',
  path: '/user/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const UserLoginRoute = UserLoginRouteImport.update({
  id: '/user/login',
  path: '/user/login',
  getParentRoute: () => rootRouteImport,
} as any)
const UserGuestRoute = UserGuestRouteImport.update({
  id: '/user/guest',
  path: '/user/guest',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardsUnemployedRoute = DashboardsUnemployedRouteImport.update({
  id: '/dashboards/unemployed',
  path: '/dashboards/unemployed',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardsStudentRoute = DashboardsStudentRouteImport.update({
  id: '/dashboards/student',
  path: '/dashboards/student',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardsRetiredRoute = DashboardsRetiredRouteImport.update({
  id: '/dashboards/retired',
  path: '/dashboards/retired',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardsGuestRoute = DashboardsGuestRouteImport.update({
  id: '/dashboards/guest',
  path: '/dashboards/guest',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardsEmployedRoute = DashboardsEmployedRouteImport.update({
  id: '/dashboards/employed',
  path: '/dashboards/employed',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardsLayoutRoute = DashboardsLayoutRouteImport.update({
  id: '/dashboards/_layout',
  path: '/dashboards',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboards': typeof DashboardsLayoutRoute
  '/dashboards/employed': typeof DashboardsEmployedRoute
  '/dashboards/guest': typeof DashboardsGuestRoute
  '/dashboards/retired': typeof DashboardsRetiredRoute
  '/dashboards/student': typeof DashboardsStudentRoute
  '/dashboards/unemployed': typeof DashboardsUnemployedRoute
  '/user/guest': typeof UserGuestRoute
  '/user/login': typeof UserLoginRoute
  '/user/signup': typeof UserSignupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboards': typeof DashboardsLayoutRoute
  '/dashboards/employed': typeof DashboardsEmployedRoute
  '/dashboards/guest': typeof DashboardsGuestRoute
  '/dashboards/retired': typeof DashboardsRetiredRoute
  '/dashboards/student': typeof DashboardsStudentRoute
  '/dashboards/unemployed': typeof DashboardsUnemployedRoute
  '/user/guest': typeof UserGuestRoute
  '/user/login': typeof UserLoginRoute
  '/user/signup': typeof UserSignupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboards/_layout': typeof DashboardsLayoutRoute
  '/dashboards/employed': typeof DashboardsEmployedRoute
  '/dashboards/guest': typeof DashboardsGuestRoute
  '/dashboards/retired': typeof DashboardsRetiredRoute
  '/dashboards/student': typeof DashboardsStudentRoute
  '/dashboards/unemployed': typeof DashboardsUnemployedRoute
  '/user/guest': typeof UserGuestRoute
  '/user/login': typeof UserLoginRoute
  '/user/signup': typeof UserSignupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/features'
    | '/how-it-works'
    | '/login'
    | '/signup'
    | '/dashboards'
    | '/dashboards/employed'
    | '/dashboards/guest'
    | '/dashboards/retired'
    | '/dashboards/student'
    | '/dashboards/unemployed'
    | '/user/guest'
    | '/user/login'
    | '/user/signup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/features'
    | '/how-it-works'
    | '/login'
    | '/signup'
    | '/dashboards'
    | '/dashboards/employed'
    | '/dashboards/guest'
    | '/dashboards/retired'
    | '/dashboards/student'
    | '/dashboards/unemployed'
    | '/user/guest'
    | '/user/login'
    | '/user/signup'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/features'
    | '/how-it-works'
    | '/login'
    | '/signup'
    | '/dashboards/_layout'
    | '/dashboards/employed'
    | '/dashboards/guest'
    | '/dashboards/retired'
    | '/dashboards/student'
    | '/dashboards/unemployed'
    | '/user/guest'
    | '/user/login'
    | '/user/signup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  FeaturesRoute: typeof FeaturesRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  DashboardsLayoutRoute: typeof DashboardsLayoutRoute
  DashboardsEmployedRoute: typeof DashboardsEmployedRoute
  DashboardsGuestRoute: typeof DashboardsGuestRoute
  DashboardsRetiredRoute: typeof DashboardsRetiredRoute
  DashboardsStudentRoute: typeof DashboardsStudentRoute
  DashboardsUnemployedRoute: typeof DashboardsUnemployedRoute
  UserGuestRoute: typeof UserGuestRoute
  UserLoginRoute: typeof UserLoginRoute
  UserSignupRoute: typeof UserSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/signup': {
      id: '/user/signup'
      path: '/user/signup'
      fullPath: '/user/signup'
      preLoaderRoute: typeof UserSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/login': {
      id: '/user/login'
      path: '/user/login'
      fullPath: '/user/login'
      preLoaderRoute: typeof UserLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/guest': {
      id: '/user/guest'
      path: '/user/guest'
      fullPath: '/user/guest'
      preLoaderRoute: typeof UserGuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboards/unemployed': {
      id: '/dashboards/unemployed'
      path: '/dashboards/unemployed'
      fullPath: '/dashboards/unemployed'
      preLoaderRoute: typeof DashboardsUnemployedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboards/student': {
      id: '/dashboards/student'
      path: '/dashboards/student'
      fullPath: '/dashboards/student'
      preLoaderRoute: typeof DashboardsStudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboards/retired': {
      id: '/dashboards/retired'
      path: '/dashboards/retired'
      fullPath: '/dashboards/retired'
      preLoaderRoute: typeof DashboardsRetiredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboards/guest': {
      id: '/dashboards/guest'
      path: '/dashboards/guest'
      fullPath: '/dashboards/guest'
      preLoaderRoute: typeof DashboardsGuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboards/employed': {
      id: '/dashboards/employed'
      path: '/dashboards/employed'
      fullPath: '/dashboards/employed'
      preLoaderRoute: typeof DashboardsEmployedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboards/_layout': {
      id: '/dashboards/_layout'
      path: '/dashboards'
      fullPath: '/dashboards'
      preLoaderRoute: typeof DashboardsLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  FeaturesRoute: FeaturesRoute,
  HowItWorksRoute: HowItWorksRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  DashboardsLayoutRoute: DashboardsLayoutRoute,
  DashboardsEmployedRoute: DashboardsEmployedRoute,
  DashboardsGuestRoute: DashboardsGuestRoute,
  DashboardsRetiredRoute: DashboardsRetiredRoute,
  DashboardsStudentRoute: DashboardsStudentRoute,
  DashboardsUnemployedRoute: DashboardsUnemployedRoute,
  UserGuestRoute: UserGuestRoute,
  UserLoginRoute: UserLoginRoute,
  UserSignupRoute: UserSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
